---
#OS1 Public
os1_auth_url: http://os1-public.osop.rhcloud.com:5000/v2.0

# Image info
os1_image_id: 34d39f49-8d93-4f92-a9c2-d3549e8d6946 #fedora 23 cloud
os1_security_group: bpms-group,default,docker-publish-ports

# User specific vars defined below should be added to user-vars.yml file
os1_user: jholmes
os1_tenant_name: "Consulting Middleware Delivery"
os1_key_name: jholmes
os1_region_name: OS1Public
os1_ip_pools: [ os1_public ]

#rhn_user:
#rhn_password:
