---
#OS1 Private
os1_auth_url: http://control.os1.phx2.redhat.com:5000/v2.0

# Image info
os1_image_id: 2695dbd9-e1b1-47a8-9ac3-4e8854aa55aa #fedora 23 cloud
os1_security_group: bpms-group
os1_flavor_id: c3.xlarge

# User specific vars defined below should be added to user-vars.yml file
os1_user: jholmes
os1_tenant_name: "Consulting Middleware Delivery"
os1_key_name: jholmes
os1_region_name: OS1Internal

#rhn_user:
#rhn_password:
