
  - name: Create first OS1 instance for kube node
    nova_compute:
      name: "jholmes-kube-node-1-{{ ansible_date_time.date }}--{{ ansible_date_time.time }}"
      state: present
      key_name: jholmes
      login_username: jholmes
      login_password: "{{ os1_password }}"
      login_tenant_name: "Consulting Middleware Delivery"
      auth_url: http://control.os1.phx2.redhat.com:5000/v2.0
      region_name: OS1Internal
      image_id: 0fe0dca2-2fb6-4260-a220-ff409de4b054 # fedora 22
      security_groups: bpms-group
      flavor_id: c3.xlarge
    register: openstack_instance_1

  - name: Create second OS1 instance for kube node
    nova_compute:
      name: "jholmes-kube-node-2-{{ ansible_date_time.date }}--{{ ansible_date_time.time }}"
      state: present
      key_name: jholmes
      login_username: jholmes
      login_password: "{{ os1_password }}"
      login_tenant_name: "Consulting Middleware Delivery"
      auth_url: http://control.os1.phx2.redhat.com:5000/v2.0
      region_name: OS1Internal
      image_id: 0fe0dca2-2fb6-4260-a220-ff409de4b054 # fedora 22
      security_groups: bpms-group
      flavor_id: c3.xlarge
    register: openstack_instance_2

  - name: Include new host into Ansible inventory
    add_host: name={{ item }} groups=nodes
    with_items:
      - "{{ openstack_instance_1.public_ip }}"
      - "{{ openstack_instance_2.public_ip }}"

  - name: Wait for SSH to be ready
    wait_for: port=22 host={{ item }} timeout=600
    with_items:
      - "{{ openstack_instance_1.public_ip }}"
      - "{{ openstack_instance_2.public_ip }}"

#  - name: Wait for SSH to be ready
#    wait_for: port=22 host={{ item }} timeout=600
#    when: openstack_instance.changed
#    with_items:
#      - "{{ openstack_instance.public_ip }}"
