---
- name: Copy Default EAP Management User/Group Configuration Files
  sudo: true
  copy:
    src: "{{ item }}"
    dest: "{{ eap_standalone_configuration_dir }}"
    owner: fedora
    group: fedora
    mode: "755"
  with_items:
    - mgmt-users.properties
    - mgmt-groups.properties  
