---
- include_vars: "os1_{{ openstack_env }}.yml"
- include_vars: "os1_flavor_{{ instance_flavor }}.yml"

- include: "{{ openstack_env }}.yml" 

- name: Include new host into Ansible inventory
  add_host: 
    name: "{{ openstack_instance.public_ip }}"  
    groups: openstack_instances

- name: Wait for SSH to be ready
  wait_for:
    port: 22
    host: "{{ openstack_instance.public_ip }}"
    timeout: 600
  when: openstack_instance.changed
