---
# This playbook deploys a kubernetes cluster 
# with the default addons.
- hosts: 127.0.0.1
  remote_user: root
  connection: local
  roles:
    - new-os1-instance
  tags:
    - new-os1-instance

  vars_prompt:
    - name: "instance_name"
      prompt: "instance name?"
      private: no
      default: bpms-design

    - name: "instance_flavor"
      prompt: "instance flavor (small, medium or large)?"
      private: no
      default: medium

    - name: "openstack_env"
      prompt: "os1 public or private?"
      private: no
      default: private

    - name: "os1_password"
      prompt: "OS1 password?"
      private: yes
      default: fakePassword            

#####################################################################################################################
#  Necessary at the playbook level (not a dependency) because host might not be bootstrapped and can't gather facts.
#  Gather Fact false can only be set at the playbook level
#####################################################################################################################

- hosts: openstack_instances
  remote_user: fedora
  sudo: true
  gather_facts: false
  roles:
    - common
  tags:
    - common

- hosts: openstack_instances
  remote_user: fedora
  roles:
    - { role: bpms-design, when: instance_name == 'bpms-design' }
  tags:
    - bpms-design

- hosts: openstack_instances
  remote_user: fedora
  sudo: true
  roles:
    - { role: file-server, when: instance_name == 'file-server' }
  tags:
    - file-server       
