# This playbox updates a fedora 22 instance and installs EAP 6.4

- name: Update Fedora 22 Instance
  hosts: 127.0.0.1
  remote_user: root
  connection: local

  vars_prompt:
    - name: "os1_password"
      prompt: "OS1 password?"
      private: yes  
      
  tasks:
    - include: tasks/fedora22.yml

